// Embedded audio only. No API credential or network requests are needed in the game.
const FlyAudio=(()=>{
 let context=null,effectsGain=null,flyGain=null,flySource=null,musicGain=null,musicSource=null,musicEnabled=true,enabled=false,running=true,loading=false;
 const buffers={},playing=new Set(),counts={};
 let effectVolume=0.65,flyVolume=0.28,musicVolume=0.18;
 const el=id=>document.getElementById(id);
 function updateGains(){if(!context)return;effectsGain.gain.setTargetAtTime(enabled?effectVolume:0,context.currentTime,0.025);flyGain.gain.setTargetAtTime(enabled&&running?flyVolume:0,context.currentTime,0.06);musicGain.gain.setTargetAtTime(enabled&&running&&musicEnabled?musicVolume:0,context.currentTime,0.06);}
 function stopEffects(){for(let source of playing){try{source.stop();}catch(_){}}playing.clear();}
 async function initialize(){if(context)return;if(typeof AudioContext==='undefined'&&typeof webkitAudioContext==='undefined')throw Error('Audio unavailable');context=new (window.AudioContext||window.webkitAudioContext)();effectsGain=context.createGain();effectsGain.connect(context.destination);flyGain=context.createGain();flyGain.gain.value=0;flyGain.connect(context.destination);musicGain=context.createGain();musicGain.gain.value=0;musicGain.connect(context.destination);await context.resume();await Promise.all(Object.entries(SOUND_DATA).map(async([name,b64])=>{let bytes=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));buffers[name]=await context.decodeAudioData(bytes.buffer);}));flySource=context.createBufferSource();flySource.buffer=buffers.fly;flySource.loop=true;flySource.connect(flyGain);flySource.start();musicSource=context.createBufferSource();musicSource.buffer=buffers.music;musicSource.loop=true;musicSource.loopEnd=38.58;musicSource.connect(musicGain);musicSource.start();}
 function movementTone(direction){let now=context.currentTime;for(let i=0;i<2;i++){let oscillator=context.createOscillator(),gain=context.createGain();oscillator.type='square';oscillator.frequency.value=(direction==='left'?660:880)*(i?0.75:1);gain.gain.setValueAtTime(0,now+i*.045);gain.gain.linearRampToValueAtTime(.22,now+i*.045+.004);gain.gain.exponentialRampToValueAtTime(.001,now+i*.045+.07);oscillator.connect(gain);gain.connect(effectsGain);oscillator.onended=()=>playing.delete(oscillator);playing.add(oscillator);oscillator.start(now+i*.045);oscillator.stop(now+i*.045+.08);}}

 function play(name,direction){if(!enabled||(!running&&name!=='over')||!buffers[name])return;if(name==='move'){movementTone(direction);counts[name]=(counts[name]||0)+1;return;}let source=context.createBufferSource();source.buffer=buffers[name];source.connect(effectsGain);source.onended=()=>playing.delete(source);playing.add(source);source.start();counts[name]=(counts[name]||0)+1;}
 async function toggle(){if(loading)return;try{loading=true;el('sound-toggle').textContent='Loading sounds…';await initialize();await context.resume();enabled=!enabled;updateGains();if(!enabled)stopEffects();el('sound-toggle').textContent=enabled?'Sound off':'Sound on';el('sound-toggle').setAttribute('aria-pressed',String(enabled));el('sound-state').textContent='Game Boy Type A · music '+(musicEnabled?'on':'off');if(enabled)play('rotate');}catch(_){el('sound-toggle').textContent='Sound on';el('sound-state').textContent='Audio could not start; click to retry';}finally{loading=false;}}
 function setRunning(value){if(running===value)return;running=value;if(!running)stopEffects();updateGains();}
 el('sound-toggle').onclick=toggle;
 el('music-toggle').onclick=async()=>{musicEnabled=!musicEnabled;if(musicEnabled&&!enabled)await toggle();updateGains();el('music-toggle').textContent=musicEnabled?'Music on':'Music off';el('music-toggle').setAttribute('aria-pressed',String(musicEnabled));el('sound-state').textContent='Game Boy Type A · music '+(musicEnabled?'on':'off');};
 el('music-volume').oninput=event=>{musicVolume=Number(event.target.value)/100;updateGains();};
 el('effects-volume').oninput=event=>{effectVolume=Number(event.target.value)/100;updateGains();};
 el('fly-volume').oninput=event=>{flyVolume=Number(event.target.value)/100;updateGains();};
 return {play,setRunning,status:()=>({enabled,running,loaded:Object.keys(buffers),events:{...counts},contextState:context?.state,effectVolume,flyVolume,musicEnabled,musicVolume,durations:Object.fromEntries(Object.entries(buffers).map(([k,v])=>[k,v.duration]))})};
})();
