const E=FlyTetris;
const $=id=>document.getElementById(id),B=$('board').getContext('2d'),F=$('fly').getContext('2d'),N=$('brain').getContext('2d');
const names=['I','O','T','S','Z','J','L'],colors=['#6ee3e9','#f5d56f','#b5a0ff','#6fe7b5','#f08cab','#85aafa','#f5ad6f'];
const featureNames=['Height','Holes','Uneven','Peak','Wells','Lines'];
$('inputs').innerHTML=featureNames.map((s,i)=>'<div class="input-item"><div class="input-bar"><i id="input'+i+'"></i></div><span id="input-label'+i+'">'+s+'</span></div>').join('');
const weights=E.effectiveWeights(MODEL.readout,MODEL.connectome.transform);
let board,cellColors,gameScore,previewPiece,lines,pieces,stream,choice,phase=0,stage=0,queue=[],qi=0,paused=false,ended=false,tickStart=0,activeX=3,activeRotation=0,press=null,progress=0,clearFlash=[];
let activePlayMs=0,lastFrameTime=null,commandApplied=false,previousX=3;
let activeY=18,previousY=18,gravityMs=0,groundedMs=0,fallAnimationMs=0,hardDropping=false,blockedCommand=null;
let releasedFeet=null,releaseStart=0,flyPosition=[350,585];
function endGame(){if(!ended){ended=true;FlyAudio.setRunning(false);FlyAudio.play('over');}}
function gameLevel(){return 1+Math.max(Math.floor(activePlayMs/30000),Math.floor(lines/10));}
function levelSpeed(){return Math.min(12,Math.pow(1.25,gameLevel()-1));}
function gravityInterval(){return 900/levelSpeed();}
function activeShape(){return E.PIECES[choice.piece][activeRotation];}
function canPlace(shape,x,y){if(x<0||x+shape.width>10||y<0||y+shape.rows.length>20)return false;return shape.rows.every((row,j)=>(board[y+j]&(row<<x))===0);}
function landingY(){let y=activeY;while(canPlace(activeShape(),activeX,y-1))y--;return y;}
function gravityStep(){if(ended||phase===3)return;if(canPlace(activeShape(),activeX,activeY-1)){previousY=activeY;activeY--;fallAnimationMs=120;groundedMs=0;}}
function updateGravity(dt){if(ended||phase===3)return;fallAnimationMs=Math.max(0,fallAnimationMs-dt);if(hardDropping){if(fallAnimationMs===0)finishLock();return;}gravityMs+=dt;while(gravityMs>=gravityInterval()){gravityMs-=gravityInterval();gravityStep();}if(!canPlace(activeShape(),activeX,activeY-1)){groundedMs+=dt;if(groundedMs>=350)finishLock();}else groundedMs=0;}
function finishLock(){if(phase===3||ended)return;lock();if(ended)return;releasedFeet=[forelegPose(-1),forelegPose(1)];releaseStart=activePlayMs;FlyAudio.play('lock');if(choice.lines)FlyAudio.play('clear');phase=3;press=null;progress=0;tickStart=lastFrameTime??0;hardDropping=false;}
const cellXY=ACTIVITY.cells.map(c=>[c.position[0],c.position[2]]);
const minX=Math.min(...cellXY.map(p=>p[0])),maxX=Math.max(...cellXY.map(p=>p[0])),minZ=Math.min(...cellXY.map(p=>p[1])),maxZ=Math.max(...cellXY.map(p=>p[1]));
const points=cellXY.map(p=>[24+(p[0]-minX)/(maxX-minX)*372,56+(p[1]-minZ)/(maxZ-minZ)*270]);
function scalar(row,features){return row.reduce((s,v,i)=>s+v*features[i],0);}

// Step-response differences are the impulse response of the same linear model.
const impulse=basis=>basis.map((step,k)=>step.map((row,n)=>row.map((v,j)=>v-(k?basis[k-1][n][j]:0))));
const liveKernel=impulse(ACTIVITY.response_basis),liveOutputKernel=impulse(ACTIVITY.output_basis);
let liveHistory=[],liveActivity=Array(ACTIVITY.cells.length).fill(0),liveOutput=Array(4).fill(0),liveInputs=Array(6).fill(0),liveElapsed=0,liveUpdates=0;
function stateInputs(){let visible=board.slice(),pose=[0,0,0];if(choice&&!ended&&phase!==3){let sh=activeShape();for(let j=0;j<sh.rows.length;j++)visible[activeY+j]|=sh.rows[j]<<activeX;pose=[activeX/Math.max(1,10-sh.width),(20-sh.rows.length-activeY)/Math.max(1,20-sh.rows.length),activeRotation/Math.max(1,E.PIECES[choice.piece].length-1)];}return E.features(visible,0).slice(0,3).concat(pose);}
function convolve(kernel){return kernel[0].map((_,n)=>liveHistory.reduce((sum,u,k)=>sum+scalar(kernel[k][n],u),0));}
function updateLiveActivity(dt=0,force=false){liveElapsed+=dt;let next=stateInputs();if(!force&&liveElapsed<100&&next.every((v,i)=>v===liveInputs[i]))return;liveElapsed=0;liveInputs=next;liveHistory.unshift(next.slice());liveHistory.length=Math.min(8,liveHistory.length);liveActivity=convolve(liveKernel);liveOutput=convolve(liveOutputKernel);liveUpdates++;}
function shownActivity(){return $('brain-mode').value==='planned'?ACTIVITY.response_basis[phase===0?0:stage].map(row=>scalar(row,choice?choice.features:Array(6).fill(0))):liveActivity;}

function evaluate(){let piece=previewPiece;previewPiece=stream();let opts=E.candidates(board,piece);if(!opts.length){endGame();return;}choice=E.choose(opts,weights);activeRotation=0;activeX=Math.min(3,10-E.PIECES[piece][0].width);previousX=activeX;activeY=20-E.PIECES[piece][0].rows.length;previousY=activeY;gravityMs=groundedMs=fallAnimationMs=0;hardDropping=false;blockedCommand=null;if(!canPlace(activeShape(),activeX,activeY)){endGame();return;}commandApplied=false;queue=[];for(let r=0;r<choice.rotation;r++)queue.push('rotate');let diff=choice.x-activeX;for(let i=0;i<Math.abs(diff);i++)queue.push(diff>0?'right':'left');queue.push('drop');qi=0;phase=0;stage=0;press=null;featureNames.forEach((_,i)=>$('input'+i).style.height=Math.max(2,choice.features[i]*100)+'%');}
function reset(){board=Array(20).fill(0);cellColors=Array.from({length:20},()=>Array(10).fill(null));gameScore=0;lines=pieces=0;stream=E.bagStream(Number($('seed').value));previewPiece=stream();ended=false;paused=false;tickStart=0;progress=0;activePlayMs=0;lastFrameTime=null;clearFlash=[];FlyAudio.setRunning(true);evaluate();releasedFeet=null;flyPosition=[350,585];liveHistory=[];liveElapsed=liveUpdates=0;updateLiveActivity(0,true);$('pause').textContent='Pause';draw(0);}
function lock(){let sh=activeShape();if(!canPlace(sh,activeX,activeY)){endGame();return;}for(let j=0;j<sh.rows.length;j++){board[activeY+j]|=sh.rows[j]<<activeX;for(let x=0;x<sh.width;x++)if(sh.rows[j]&(1<<x))cellColors[activeY+j][activeX+x]=colors[choice.piece];}clearFlash=[];board.forEach((row,i)=>{if(row===1023)clearFlash.push(i);});let after=board.filter(row=>row!==1023);while(after.length<20)after.push(0);choice={...choice,board:after,lines:clearFlash.length};}
function commit(){cellColors=cellColors.filter((_,i)=>!clearFlash.includes(i));while(cellColors.length<20)cellColors.push(Array(10).fill(null));board=choice.board;gameScore+=[0,100,300,500,800][choice.lines];lines+=choice.lines;pieces++;clearFlash=[];if(pieces===2000){ended=true;return;}evaluate();}
function applyCommand(){if(commandApplied||phase!==2)return;previousX=activeX;let key=queue[qi];blockedCommand=null;if(key==='rotate'){let next=(activeRotation+1)%E.PIECES[choice.piece].length,shape=E.PIECES[choice.piece][next],y=activeY+activeShape().rows.length-shape.rows.length;let kick=[0,-1,1,-2,2].find(dx=>canPlace(shape,activeX+dx,y));if(kick!==undefined){activeRotation=next;activeX+=kick;activeY=y;previousY=y;fallAnimationMs=0;}else blockedCommand='rotate';}else if(key==='left'||key==='right'){let dx=key==='left'?-1:1;if(canPlace(activeShape(),activeX+dx,activeY))activeX+=dx;else blockedCommand=key;}else if(key==='drop'){previousY=activeY;activeY=landingY();fallAnimationMs=180;hardDropping=true;}FlyAudio.play(blockedCommand?'lock':key==='left'||key==='right'?'move':key,key);commandApplied=true;}
function advance(){if(ended)return;if(phase===0){phase=1;stage=0;}else if(phase===1){if(stage<7)stage++;else{phase=2;press=queue[0];commandApplied=false;}}else if(phase===3){commit();}else{let key=queue[qi];applyCommand();if(key==='drop'){finishLock();return;}qi++;press=queue[qi];commandApplied=false;previousX=activeX;}progress=0;}
function roundRect(ctx,x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.stroke();}}
function ellipse(ctx,x,y,rx,ry,angle,fill,stroke){ctx.beginPath();ctx.ellipse(x,y,rx,ry,angle,0,Math.PI*2);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.stroke();}}
function line(ctx,points,color,width){ctx.beginPath();ctx.moveTo(...points[0]);points.slice(1).forEach(p=>ctx.lineTo(...p));ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineCap='round';ctx.lineJoin='round';ctx.stroke();}
function drawBoard(){B.fillStyle='#080c13';B.fillRect(0,0,220,440);for(let y=0;y<20;y++)for(let x=0;x<10;x++){B.strokeStyle='#172332';B.lineWidth=0.5;B.strokeRect(x*22,(19-y)*22,22,22);if(cellColors[y][x]){roundRect(B,x*22+1,(19-y)*22+1,20,20,2,clearFlash.includes(y)&&Math.floor(progress*8)%2===0?'#ffffff':cellColors[y][x]);B.fillStyle='#ffffff35';B.fillRect(x*22+2,(19-y)*22+2,18,3);}}if(choice&&!ended&&phase!==3){let sh=E.PIECES[choice.piece][activeRotation];let x=Math.max(0,Math.min(activeX,10-sh.width));let drawX=x;if(phase===2&&(press==='left'||press==='right')&&commandApplied)drawX=previousX+(x-previousX)*Math.min(1,Math.max(0,(progress-0.45)/0.3));let landing=landingY();let sy=activeY;if(fallAnimationMs>0)sy=activeY+(previousY-activeY)*Math.min(1,fallAnimationMs/(hardDropping?180:120));for(let j=0;j<sh.rows.length;j++)for(let a=0;a<sh.width;a++)if(sh.rows[j]&(1<<a)){roundRect(B,(drawX+a)*22+1,(19-landing-j)*22+1,20,20,2,null,'#447668');roundRect(B,(drawX+a)*22+1,(19-sy-j)*22+1,20,20,2,colors[choice.piece]);B.fillStyle='#ffffff55';B.fillRect((drawX+a)*22+2,(19-sy-j)*22+2,18,3);}}$('piece-name').textContent=choice?names[choice.piece]+' piece':'';$('lines').textContent=lines;$('pieces').textContent=pieces;$('height').textContent=Math.round(E.features(board,0)[3]*20);$('game-score').textContent=gameScore;let ctx=$('next').getContext('2d');ctx.clearRect(0,0,90,55);let sh=E.PIECES[previewPiece][0];for(let y=0;y<sh.rows.length;y++)for(let x=0;x<sh.width;x++)if(sh.rows[y]&(1<<x))roundRect(ctx,8+x*18,37-y*18,16,16,2,colors[previewPiece]);}
const keyCenters={left:230,right:310,rotate:410,drop:270},keyLabels={left:'←',right:'→',rotate:'↻',drop:'↓'};
function updateFlyPose(dt){if(!dt)return;let target=[350,585];if(phase===2&&press){let side=(press==='left'||press==='right')?-1:1;target=[keyCenters[press]-side*46,(press==='drop'?560:520)+36];}else if(phase===3)target=flyPosition;let q=1-Math.exp(-dt/85);flyPosition=flyPosition.map((v,i)=>v+(target[i]-v)*q);}
function drawFly(time){F.clearRect(0,0,600,690);drawHandheld();let [cx,cy]=flyPosition;
 // A small dorsal fly, facing the LCD. Thin insect legs replace human-like arms.
 const moving=phase===2&&progress<.4,walk=moving?Math.sin(activePlayMs*.028)*4:0;
 for(let side of [-1,1])for(let pair=0;pair<2;pair++){let root=[cx+side*12,cy+pair*14],elbow=[cx+side*(31+pair*3),cy+10+pair*18+side*walk],tip=[cx+side*(38+pair*5),cy+28+pair*21-side*walk];line(F,[root,elbow,tip],'#424843',2.2);}

 let flutter=.06*Math.sin(activePlayMs*.24);
 for(let side of [-1,1]){ellipse(F,cx+side*23,cy+19,15,43,side*(-.38+flutter),'#c7d4c943','#b1bfb17a');line(F,[[cx+side*9,cy-3],[cx+side*25,cy+34],[cx+side*34,cy+51]],'#7f93815e',.8);}
 ellipse(F,cx,cy+29,13,29,0,'#343c32','#59634f');for(let y=cy+10;y<cy+52;y+=8)line(F,[[cx-10,y],[cx+10,y]],'#1c241d',2);
 ellipse(F,cx,cy,19,23,0,'#424b3a','#6c785c');for(let side of [-1,1])for(let i=0;i<3;i++)line(F,[[cx+side*(10+i*2),cy-4+i*7],[cx+side*(17+i*2),cy-10+i*7]],'#a2aa8777',.7);
 ellipse(F,cx,cy-29,19,15,0,'#353d31','#707c60');for(let side of [-1,1]){ellipse(F,cx+side*13,cy-30,10,13,side*.15,'#733c36','#9d5e48');for(let i=0;i<5;i++)ellipse(F,cx+side*13+(i%2)*3-1,cy-36+i*3,1.2,1.2,0,'#bc7a5d55');line(F,[[cx+side*5,cy-39],[cx+side*8,cy-46],[cx+side*13,cy-49]],'#515c42',1.4);}
 let glow=Math.min(.55,shownActivity().reduce((sum,v)=>sum+Math.abs(v),0)/ACTIVITY.cells.length*2);ellipse(F,cx,cy-29,4,4,0,'rgba(111,231,207,'+glow+')');
 for(let side of [-1,1]){let tip=forelegPose(side),root=[cx+side*13,cy-13],dx=tip[0]-root[0],dy=tip[1]-root[1],length=Math.max(1,Math.hypot(dx,dy));let elbow=[(root[0]+tip[0])/2+side*dy/length*12,(root[1]+tip[1])/2-side*dx/length*12];let wrist=[elbow[0]+(tip[0]-elbow[0])*.8,elbow[1]+(tip[1]-elbow[1])*.8];let active=phase===2&&((side===-1&&(press==='left'||press==='right'))||(side===1&&(press==='rotate'||press==='drop')));line(F,[root,elbow,wrist,tip],active?'#a3ad80':'#758264',active?3.1:2.3);ellipse(F,...tip,active?3.5:2.5,2,0,active?'#596943':'#35462e');}
}
function smoothMotion(v){v=Math.max(0,Math.min(1,v));return v*v*(3-2*v);}
function keyDepression(p){return p<0.45?0:p<0.53?smoothMotion((p-0.45)/0.08):p<0.72?1:1-smoothMotion((p-0.72)/0.08);}
function forelegPose(side){const rest=[flyPosition[0]+side*30,flyPosition[1]-28];if(phase===3&&releasedFeet){let q=smoothMotion((activePlayMs-releaseStart)/180),from=releasedFeet[side===-1?0:1];return from.map((v,i)=>v+(rest[i]-v)*q);}let controls=side===-1?(press==='left'||press==='right'):(press==='rotate'||press==='drop');if(phase!==2||!controls)return rest;let reach=progress<.4?smoothMotion(progress/.4):progress<.8?1:1-smoothMotion((progress-.8)/.2),targetY=press==='drop'?560:520;return [rest[0]+(keyCenters[press]-rest[0])*reach,rest[1]+(targetY-rest[1])*reach-8*Math.sin(Math.PI*reach)+keyDepression(progress)*5];}



function drawHandheld(){
 const ctx=F;
 roundRect(ctx,121,16,358,654,35,'#06080a','#4a4d51');roundRect(ctx,129,21,342,644,30,'#202225','#373a3d');
 roundRect(ctx,142,51,316,385,12,'#090b0c','#626563');roundRect(ctx,155,65,290,350,4,'#a4ad87','#656c54');
 ctx.fillStyle='#1c2b20';ctx.font='bold 12px monospace';ctx.textAlign='left';ctx.fillText('SCORE',356,95);ctx.font='bold 18px monospace';ctx.fillText(String(gameScore).padStart(6,'0'),355,120);ctx.font='11px monospace';ctx.fillText('NEXT',356,147);
 function lcdBlock(x,y,size=15,dim=false){ctx.globalAlpha=dim?.055:1;ctx.strokeStyle='#263326';ctx.lineWidth=1.6;ctx.strokeRect(x+1,y+1,size-2,size-2);ctx.fillStyle='#263326';ctx.fillRect(x+4,y+4,size-8,size-8);ctx.globalAlpha=1;}
 ctx.strokeStyle='#384335';ctx.lineWidth=2;ctx.strokeRect(174,83,165,324);
 for(let y=0;y<20;y++)for(let x=0;x<10;x++)lcdBlock(177+x*16,87+(19-y)*16,15,!(board[y]&(1<<x)));
 if(choice&&!ended&&phase!==3){let sh=activeShape(),x=activeX,y=activeY;if(phase===2&&(press==='left'||press==='right')&&commandApplied)x=previousX+(activeX-previousX)*Math.min(1,Math.max(0,(progress-.45)/.3));if(fallAnimationMs>0)y+= (previousY-activeY)*Math.min(1,fallAnimationMs/(hardDropping?180:120));for(let j=0;j<sh.rows.length;j++)for(let a=0;a<sh.width;a++)if(sh.rows[j]&(1<<a))lcdBlock(177+(x+a)*16,87+(19-y-j)*16);}
 let next=E.PIECES[previewPiece][0];for(let y=0;y<next.rows.length;y++)for(let x=0;x<next.width;x++)if(next.rows[y]&(1<<x))lcdBlock(359+x*14,172-y*14,13);
 ctx.fillStyle='#243125';ctx.font='bold 22px monospace';ctx.fillText(String(gameLevel()).padStart(2,'0'),370,237);ctx.font='11px monospace';ctx.fillText('SPEED LEVEL',354,255);ctx.fillText('LINES '+lines,354,282);ctx.fillText(ended?'GAME OVER':paused?'PAUSED':'TETRIS',354,323);
 ctx.textAlign='center';ctx.fillStyle='#e4e6de';ctx.font='bold 12px system-ui';ctx.fillText('CLASSIC',300,39);
 drawDeviceButton(270,480,18,'↑','up');drawDeviceButton(230,520,18,'←','left');drawDeviceButton(310,520,18,'→','right');drawDeviceButton(270,560,18,'↓','drop');drawDeviceButton(410,520,29,'↻','rotate');
 ctx.font='bold 12px system-ui';ctx.fillStyle='#e7e7df';ctx.fillText('BRICK GAME',185,627);ctx.font='8px monospace';ctx.fillStyle='#9b9e99';ctx.fillText('9999 IN 1',185,642);

}
function drawDeviceButton(x,y,r,label,key){let lit=phase===2&&press===key&&commandApplied&&progress>=.45&&progress<.8,down=lit?keyDepression(progress)*5:0;ellipse(F,x,y+4,r+2,r+2,0,'#050606');ellipse(F,x,y+down,r,r,0,lit?'#fff383':'#f3d935','#a99a30');F.fillStyle='#6b621d';F.font=(key==='rotate'?'22':'15')+'px system-ui';F.textAlign='center';F.fillText(label,x,y+5+down);}
function manualDeviceKey(key){if(ended||phase===3)return;let saved={phase,queue,qi,press,commandApplied};phase=2;queue=[key];qi=0;press=key;commandApplied=false;applyCommand();({phase,queue,qi,press,commandApplied}=saved);updateLiveActivity(0,true);draw(performance.now());}
function handheldClick(event){let rect=$('fly').getBoundingClientRect(),x=(event.clientX-rect.left)*600/rect.width,y=(event.clientY-rect.top)*690/rect.height;if(Math.hypot(x-270,y-480)<23){manualDeviceKey('rotate');return;}for(let key of ['left','right','rotate','drop']){let ky=key==='drop'?560:520;if(Math.hypot(x-keyCenters[key],y-ky)<(key==='rotate'?34:23)){manualDeviceKey(key);return;}}}

function drawBrain(){N.fillStyle='#101722';N.fillRect(0,0,420,435);N.textAlign='center';N.fillStyle='#92a1b8';N.font='11px system-ui';N.fillText('Actual annotated neuron positions · x/z projection',210,25);const current=phase===0?0:stage;let basis=ACTIVITY.response_basis[current],f=choice?choice.features:Array(6).fill(0);let planned=$('brain-mode').value==='planned';let activity=shownActivity();let labels=planned?featureNames:['Height','Holes','Uneven','Piece X','Descent','Rotation'];let inputs=planned?f:liveInputs;labels.forEach((label,i)=>{$('input-label'+i).textContent=label;$('input'+i).style.height=Math.max(2,inputs[i]*100)+'%';});for(let i=0;i<points.length;i++){let v=activity[i],a=Math.min(1,Math.abs(v)*7);N.globalAlpha=0.17+0.83*a;N.fillStyle=v<0?'#f08cab':'#6fe7cf';N.beginPath();N.arc(points[i][0],points[i][1],1+2*a,0,Math.PI*2);N.fill();}N.globalAlpha=1;N.font='11px system-ui';N.fillStyle='#92a1b8';N.fillText('Descending readout groups · normalized model units',210,351);let out=planned?ACTIVITY.output_basis[current].map(row=>scalar(row,f)):liveOutput;for(let g=0;g<4;g++){let x=32+g*99;roundRect(N,x,365,73,7,3,'#243549');roundRect(N,x,365,Math.min(73,Math.abs(out[g])*160),7,3,out[g]<0?'#f08cab':'#6fe7cf');N.fillStyle='#b5c3d4';N.fillText('G'+(g+1)+'  '+out[g].toFixed(3),x+36,392);}$('brain-step').textContent=planned?(current+1)+' / 8':'Live · update '+liveUpdates;$('brain-state').textContent=planned?'Candidate placement inputs · trained policy':'Current piece: column '+activeX+' · row '+activeY+' · rotation '+activeRotation+' · 8-update response window';let score=choice?scalar(weights,choice.features):0;$('score').textContent='Planned placement score: '+score.toFixed(4);}
function draw(time){drawBoard();drawFly(time);drawBrain();for(let i=0;i<3;i++)$('phase'+i).classList.toggle('active',Math.min(phase,2)===i);$('action').textContent=ended?(pieces===2000?'Reached the 2,000-piece demo cap':'Game over — top-out'):phase===0?'Evaluate candidate placements for '+names[choice.piece]:phase===1?'Propagate model activity · update '+(stage+1)+' of 8':phase===3?(choice.lines?'Clear '+choice.lines+' line'+(choice.lines===1?'':'s')+'!':'Piece locked; next piece'):'Foreleg press: '+press.toUpperCase()+' · '+(qi+1)+' / '+queue.length;$('run-state').textContent=ended?'Finished':paused?'Paused':'Running';$('command-queue').innerHTML=queue.map((key,i)=>'<span style="border:1px solid '+(phase===2&&i===qi?'#6fe7cf':'#344553')+';border-radius:5px;padding:4px 10px;color:'+(phase===2&&i===qi?'#6fe7cf':i<qi?'#617386':'#b2c1d2')+'">'+keyLabels[key]+'</span>').join('');$('level').textContent='Level '+gameLevel()+' · '+levelSpeed().toFixed(2)+'× falling speed';$('speed-note').textContent='Automatic gravity: one row every '+Math.round(gravityInterval())+' ms. Next timed level in '+Math.ceil((30000-activePlayMs%30000)/1000)+'s. The fly reaction speed stays fixed. Pause freezes everything.';$('gravity-status').textContent=ended?'Game over':phase===3?'Locked — next piece incoming':'Automatic fall · '+(20-activeY-activeShape().rows.length)+' rows from spawn';if(blockedCommand&&phase===2)$('action').textContent+=' — blocked by stack';}
function duration(){let base=phase===0?500:phase===1?130:phase===3?(choice.lines?650:230):750;return base/Number($('speed').value);}
function tick(t){if(!tickStart)tickStart=t;let dt=lastFrameTime===null?0:Math.max(0,Math.min(100,t-lastFrameTime));lastFrameTime=t;if(!paused&&!ended){let gameDt=dt*Number($('speed').value);let oldLevel=gameLevel();activePlayMs+=gameDt;let oldPhase=phase;updateGravity(gameDt);if(phase!==oldPhase)tickStart=t;progress=Math.min(1,(t-tickStart)/duration());if(phase===2&&progress>=0.45)applyCommand();if(progress>=1){advance();tickStart=t;}if(!ended&&gameLevel()>oldLevel)FlyAudio.play('level');updateFlyPose(gameDt);updateLiveActivity(gameDt);}FlyAudio.setRunning(!paused&&!ended);draw(t);requestAnimationFrame(tick);}
$('pause').onclick=()=>{paused=!paused;FlyAudio.setRunning(!paused&&!ended);$('pause').textContent=paused?'Resume':'Pause';if(!paused)tickStart=performance.now()-progress*duration();};$('step').onclick=()=>{paused=true;FlyAudio.setRunning(false);$('pause').textContent='Resume';advance();updateLiveActivity(0,true);tickStart=performance.now();draw(tickStart);};$('restart').onclick=reset;
$('brain').onpointermove=event=>{let rect=$('brain').getBoundingClientRect(),x=(event.clientX-rect.left)*420/rect.width,y=(event.clientY-rect.top)*435/rect.height;let index=-1,dist=12;points.forEach((p,i)=>{let d=Math.hypot(p[0]-x,p[1]-y);if(d<dist){dist=d;index=i;}});if(index>=0){let c=ACTIVITY.cells[index],v=shownActivity()[index];$('neuron-info').textContent=c.group+' · '+c.root_id+' · response '+v.toFixed(4);}else $('neuron-info').textContent='1,000 sampled cells · annotated x/z positions';};
$('fly').onclick=handheldClick;
$('brain-mode').onchange=()=>draw(performance.now());
reset();requestAnimationFrame(tick);
