const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const sources=[],gains=[],els={};
class MockContext{constructor(){this.state='running';this.currentTime=0;this.destination={};}resume(){return Promise.resolve();}createBuffer(channels,length,rate){const data=new Float32Array(length);return {duration:length/rate,getChannelData:()=>data};}createOscillator(){let source=this.createBufferSource();source.frequency={value:0};return source;}createGain(){let gain={value:0,setTargetAtTime(v){this.value=v;},setValueAtTime(v){this.value=v;},linearRampToValueAtTime(v){this.value=v;},exponentialRampToValueAtTime(v){this.value=v;}},g={gain,connect(){}};gains.push(g);return g;}decodeAudioData(bytes){assert(bytes.byteLength>1000);return Promise.resolve({duration:1});}createBufferSource(){let source={connect(){},start(){this.started=true;},stop(){this.stopped=true;}};sources.push(source);return source;}}
const document={getElementById(id){return els[id]??={setAttribute(k,v){this[k]=v;}};}};
const soundNames=['move','rotate','drop','lock','clear','level','over','fly','music'];
const SOUND_DATA=Object.fromEntries(soundNames.map(k=>[k,fs.readFileSync(path.join(__dirname,'sounds',(k==='music'?'music-original.ogg':k+'.mp3'))).toString('base64')]));
const c=vm.createContext({document,AudioContext:MockContext,window:{AudioContext:MockContext},SOUND_DATA,Uint8Array,atob:s=>Buffer.from(s,'base64').toString('binary')});
vm.runInContext(fs.readFileSync(path.join(__dirname,'sounds.js'),'utf8'),c);
(async()=>{
 await els['sound-toggle'].onclick();assert.equal(vm.runInContext('FlyAudio.status().enabled',c),true);assert.equal(vm.runInContext('FlyAudio.status().loaded.length',c),9);
 assert(sources[0].loop&&sources[0].started,'Fly loop did not start');assert(gains[1].gain.value>0);assert(sources[1].loop&&sources[1].started,'Music loop did not start');assert.equal(sources[1].loopEnd,38.58);assert(sources[1].buffer,'Original music buffer missing');assert(gains[2].gain.value>0);await els['music-toggle'].onclick();assert.equal(gains[2].gain.value,0);assert(vm.runInContext('FlyAudio.status().enabled',c),'Music toggle muted effects');await els['music-toggle'].onclick();assert(gains[2].gain.value>0);let start=sources.length;vm.runInContext('FlyAudio.play("move","left");FlyAudio.play("move","right");',c);assert.equal(sources.length,start+4);assert.equal(sources[start].frequency.value,660);assert.equal(sources[start+2].frequency.value,880);els['music-volume'].oninput({target:{value:30}});assert.equal(vm.runInContext('FlyAudio.status().musicVolume',c),0.3);
 vm.runInContext('FlyAudio.play("move");FlyAudio.setRunning(false);',c);assert.equal(gains[1].gain.value,0);assert.equal(gains[2].gain.value,0);assert(sources.at(-1).stopped,'Pause failed to stop effects');
 let count=sources.length;vm.runInContext('FlyAudio.play("move");',c);assert.equal(sources.length,count);
 vm.runInContext('FlyAudio.play("over");',c);assert.equal(sources.length,count+1);assert(!sources.at(-1).stopped,'Game-over cue cut off');
 await els['sound-toggle'].onclick();assert.equal(vm.runInContext('FlyAudio.status().enabled',c),false);assert(sources.at(-1).stopped);assert.equal(gains[0].gain.value,0);
 els['effects-volume'].oninput({target:{value:20}});els['fly-volume'].oninput({target:{value:5}});assert.equal(vm.runInContext('FlyAudio.status().effectVolume',c),0.2);assert.equal(vm.runInContext('FlyAudio.status().flyVolume',c),0.05);
 console.log('PASS: 9 embedded clips including the original Type A recording, user-gesture activation, looping fly, pause/mute, independent volumes, independent music toggle/volume, audible left/right oscillator cues, and game-over cue survives stopping the game.');
})().catch(e=>{console.error(e);process.exitCode=1;});
